language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.5.3
  - 2.4.5

bundler_args: "--without documentation --path bundle"

before_install:
  - git fetch --depth=1000000
  - gem install bundler

after_install:
  - rake install

script:
  - echo "Running the Dangerfile for this repo"
  - bundle exec danger --verbose
